let gameSeq = []; // stores the sequence generated by the game
let userSeq = []; // stores the sequence entered by the user
let btns = ["yellow","red","green","blue"]; // array of all button colors

let h2 = document.querySelector("h2"); // select the <h2> element
h2.addEventListener("mouseover",function(){ // when mouse hovers over h2
    if(h2.innerText =="press any key or CLICK HERE to start the game"){
        h2.style.color = "blue";// color will change to blue when hover h2
    }
});
h2.addEventListener("mouseout",function(){ // when mouse leaves h2
    if(h2.innerText =="press any key or CLICK HERE to start the game"){
        h2.style.color = "";// color will change back to normal
    }
});

let started = false; // flag to check if game started
let level = 0; // current level
let highScore = 0; // stores highest score

document.addEventListener("keypress",function(){ // any keypress to start the game
    if(started ==false){
        console.log("game is started"); // log in console
        started = true; // mark game as started
        levelUp(); // call first level
    }
});
h2.addEventListener("click",function(){ // click on h2 to start the game
    if(started ==false){
        console.log("game is started"); // log in console
        started = true; // mark game as started
        levelUp(); // call first level
    }
});

function gameFlash(btn){ // flashes the game-selected button
    btn.classList.add("gameFlash"); // add CSS class for flash
    setTimeout(function(){
        btn.classList.remove("gameFlash") // remove flash after 300ms
    },300);
}
function userFlash(btn){ // flashes the user-selected button
    btn.classList.add("userFlash"); // add CSS class for flash
    setTimeout(function(){
        btn.classList.remove("userFlash") // remove flash after 300ms
    },300);
}
function levelUp(){ // function to increase level and show next sequence
    userSeq = []; // reset user sequence for new level
    level++; // increase level count
    h2.style.color = "green"; // change h2 color to green
    h2.innerText = `Level ${level}`; // display current level
    
    let randIdx = Math.floor(Math.random() * 4); // random index 0-3
    let randColor = btns[randIdx]; // pick random color
    let randBtn = document.querySelector(`.${randColor}`); // get random button

    gameSeq.push(randColor); // push random color to game sequence
    console.log(gameSeq); // print sequence in console
    gameFlash(randBtn); // flash the selected button
}

function buttonPress(){ // when user clicks a button
    let btn = this; // "this" = clicked button
    userFlash(btn); // flash clicked button
    let userColor = btn.getAttribute("id"); // get button id (color)
    userSeq.push(userColor); // push into user sequence

    checkAns(userSeq.length-1); // check the latest answer
}

let allBtns = document.querySelectorAll(".btn"); // select all buttons
for(btn of allBtns){ // loop through each button
    btn.addEventListener("click",buttonPress) // add click event
}

function checkAns(idx){ // check user answer with game sequence
    if(userSeq[idx]===gameSeq[idx]){ // if correct
       if(userSeq.length == gameSeq.length){ // if user completed full sequence
        setTimeout(levelUp,1000); // move to next level after delay
       }
    }
       else{ // if wrong answer
            // update high score if beaten
            if(level > highScore){
                highScore = level; // update high score
                h3.innerText = `High score = ${highScore}`; // update <h3> text
            }
            h2.innerHTML = `Game over !Your score was <b>${level}<b> <br>press any key to restart `; // show game over
            h2.style.color = "red"; // set text red
            document.querySelector("body").style.backgroundColor = "red"; // flash red background
            h2.style.color = "black"; // immediately change to black (overrides red)
            setTimeout(function(){
            document.querySelector("body").style.backgroundColor = "white"; // back to white
            h2.style.color = "red"; // text red again
            },200);

            reset(); // reset game
        }
    }

function reset(){    // reset variables for restart
    started = false; // resets game to not started
    gameSeq=[]; // clear game sequence
    userSeq=[]; // clear user sequence
    level = 0;  // reset level
}

//high score
let h3 = document.querySelector("h3"); // select the <h3> element for high score
